import { calculateCost } from './cost-calculator.js';

/**
 * Token Event Parser — Domain Layer
 *
 * Responsibility: Parse StepFinishEvent → TokenRecord
 * Zero business logic, pure data transformation
 * Zero I/O, zero external dependencies
 */

/**
 * Token usage breakdown captured from a model/tool execution step.
 */
export interface TokenUsage {
  /**
   * Input tokens used by the step.
   */
  input: number;

  /**
   * Output tokens generated by the step.
   */
  output: number;

  /**
   * Reasoning tokens used by the step.
   */
  reasoning: number;

  /**
   * Cache read/write token counts.
   */
  cache: { read: number; write: number };
}

/**
 * Routing decision used to correlate token usage with a selected tier.
 */
export interface RoutingDecision {
  /**
   * Selected tier name.
   */
  tier: 'fast' | 'medium' | 'heavy' | 'unknown';

  /**
   * Cost ratio multiplier for the selected tier.
   */
  costRatio: number;

  /**
   * Optional estimated input/output token counts used for cost comparison.
   */
  estimated?: { input: number; output: number };
}

/**
 * Domain token record persisted and aggregated for a session.
 */
export interface TokenRecord {
  /**
   * OpenCode session ID associated with the step.
   */
  sessionId: string;

  /**
   * Unix timestamp of the captured step.
   */
  timestamp: number;

  /**
   * Actual token usage captured from the execution.
   */
  actualTokens: TokenUsage;

  /**
   * Actual cost associated with the execution.
   */
  realCost: number;

  /**
   * Tier selected by the router for this step.
   */
  delegatedTier: 'fast' | 'medium' | 'heavy' | 'unknown';

  /**
   * Model used for the step.
   */
  modelUsed: string;

  /**
   * Optional estimated input/output token counts from routing.
   */
  estimatedTokens?: { input: number; output: number };

  /**
   * Optional estimated cost from routing.
   */
  estimatedCost?: number;

  /**
   * Tier accuracy grade calculated by the aggregator.
   */
  tierAccuracy: 'OPTIMAL' | 'RIGHT' | 'ACCEPTABLE' | 'SUBOPTIMAL' | 'OVERSHOT' | 'UNKNOWN';

  /**
   * Estimation error as percentages for input and output tokens.
   */
  estimationError: {
    /**
     * Input token estimation error percentage.
     */
    input: number;

    /**
     * Output token estimation error percentage.
     */
    output: number;
  };

  /**
   * Total tokens used for cost and report calculations.
   */
  totalTokensUsed: number;
}

/**
 * Raw step-finish event emitted by a tool execution hook.
 */
export interface StepFinishEvent {
  /**
   * Event type, expected to be `step-finish`.
   */
  type?: 'step-finish';

  /**
   * OpenCode session ID associated with the step.
   */
  sessionID: string;

  /**
   * Optional Unix timestamp for the event.
   */
  timestamp?: number;

  /**
   * Actual cost associated with the event.
   */
  cost: number;

  /**
   * Actual token usage captured from the event.
   */
  tokens: TokenUsage;
}

/**
 * TokenEventParser interface
 *
 * Port: abstraction for parsing StepFinishEvent into domain TokenRecord.
 * Allows testing with mock implementations.
 */
export interface TokenEventParser {
  /**
   * Parse a step-finish event into a TokenRecord.
   * If routingDecision is provided, correlate event with decision.
   * If not, record will have delegatedTier='unknown'.
   *
   * @param event - Raw step-finish event to parse.
   * @param routingDecision - Optional routing decision to correlate with the parsed record.
   * @returns Parsed token record with actual usage and optional routing metadata.
   */
  parse(event: StepFinishEvent, routingDecision?: RoutingDecision): TokenRecord;
}

/**
 * DefaultTokenEventParser
 *
 * Reference implementation: straightforward parsing with no business logic.
 */
export class DefaultTokenEventParser implements TokenEventParser {
  /**
   * Parse a step-finish event into a domain token record.
   *
   * The parser preserves actual token usage and cost, fills timestamp defaults,
   * and adds optional routing metadata when a decision is provided.
   *
   * @param event - Raw step-finish event to parse.
   * @param routingDecision - Optional routing decision to correlate with the parsed record.
   * @returns Parsed token record with actual usage and optional routing metadata.
   * @example
   * ```ts
   * const parser = new DefaultTokenEventParser();
   * const record = parser.parse(event);
   * ```
   */
  parse(event: StepFinishEvent, routingDecision?: RoutingDecision): TokenRecord {
    const totalTokensUsed = event.tokens.input +
                           event.tokens.output +
                           event.tokens.reasoning +
                           event.tokens.cache.read;

    const record: TokenRecord = {
      sessionId: event.sessionID,
      timestamp: event.timestamp ?? Date.now(),
      actualTokens: event.tokens,
      realCost: event.cost,
      delegatedTier: routingDecision?.tier ?? 'unknown',
      modelUsed: 'unknown', // will be enriched from context if needed
      estimatedTokens: routingDecision?.estimated,
      estimatedCost: routingDecision?.estimated && calculateCost(routingDecision.estimated, { costRatio: routingDecision.costRatio }),
      tierAccuracy: 'UNKNOWN', // will be calculated by aggregator
      estimationError: { input: 0, output: 0 }, // will be calculated by aggregator
      totalTokensUsed,
    };

    return record;
  }
}
